spring:
  application:
    name:
      payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-service-group
    properties:
      schema.registry.url: http://localhost:8081
server:
  port: 7071

kafka:
  topic:
    order-created: order.created

