spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mongodb:
    uri: mongodb://mongo:mongo@mongodb:27017/orderdb?authSource=admin

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081

app:
  kafka:
    topic:
      order-created: order.created
server:
  port: 8083